name: Inception

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    restart: unless-stopped
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb
    restart: unless-stopped
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: unless-stopped

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password
  db_password:
    file: ../secrets/db_password
  wp_admin_password:
    file: ../secrets/wp_admin_password
  wp_user_password:
    file: ../secrets/wp_user_password
