name: 42_Inception

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    restart: unless-stopped
  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    restart: unless-stopped
  nginx:

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
  wordpress_data:
    name: wordpress_data

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
